<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="8" errors="1" failures="7" skip="0"><testcase classname="test_root.Test_Root_test1" name="test_Root_A" time="0.000"><failure type="builtins.AssertionError" message="Not implemented"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/test_root.py", line 8, in test_Root_A
    self.fail("Not implemented")
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Not implemented
]]></failure></testcase><testcase classname="test4.Test_test3" name="test4A" time="0.000"><failure type="builtins.AssertionError" message="Not implemented"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/test4.py", line 6, in test4A
    self.fail("Not implemented")
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Not implemented
]]></failure></testcase><testcase classname="test_unittest_one.Test_test1" name="test_A" time="0.000"><failure type="builtins.AssertionError" message="Not implemented"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/test_unittest_one.py", line 8, in test_A
    self.fail("Not implemented")
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Not implemented
]]></failure></testcase><testcase classname="test_unittest_two.Test_test2" name="test_A2" time="0.000"><failure type="builtins.AssertionError" message="Not implemented"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/test_unittest_two.py", line 5, in test_A2
    self.fail("Not implemented")
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Not implemented
]]></failure></testcase><testcase classname="test_unittest_two.Test_test2" name="test_C2" time="0.000"><failure type="builtins.AssertionError" message="1 != 2 : Not equal"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/test_unittest_two.py", line 11, in test_C2
    self.assertEqual(1,2,'Not equal')
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2 : Not equal
]]></failure></testcase><testcase classname="test_unittest_two.Test_test2" name="test_D2" time="0.000"><error type="builtins.ArithmeticError" message=""><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/test_unittest_two.py", line 14, in test_D2
    raise ArithmeticError()
ArithmeticError
]]></error></testcase><testcase classname="test_unittest_two.Test_test2a" name="test_222A2" time="0.000"><failure type="builtins.AssertionError" message="Not implemented"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/test_unittest_two.py", line 19, in test_222A2
    self.fail("Not implemented")
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Not implemented
]]></failure></testcase><testcase classname="unittest_three_test.Test_test3" name="test_A" time="0.000"><failure type="builtins.AssertionError" message="Not implemented"><![CDATA[Traceback (most recent call last):
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/donjayamanne/.vscode/extensions/pythonVSCode/src/test/pythonFiles/testFiles/noseFiles/tests/unittest_three_test.py", line 6, in test_A
    self.fail("Not implemented")
  File "/Users/donjayamanne/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: Not implemented
]]></failure></testcase></testsuite>
