Update debugpy to 1.5.1 to ensure user-unhandled exception setting is false by default.
