Fix for UriError when using python.interpreterPath command in tasks.
