Fix python.dataScience.maxOutputSize to be honored again.
